### ISSUE TITLE
switch to node 20

### ISSUE THREAD

**Issue by pjfanning** [manusa/actions-setup-minikube#111]
GitHub CI now warns if actions use Node 16 and they seem to want to remove support for it soon.

**Comment by kabir** [comment]
I just noticed this too

**Comment by manusa** [comment]
Hi, apparently I began to work on this a few weeks ago but got caught into something else and completely forgot about it :facepalm: 

@pjfanning thanks for the PR, I'll create a new release as soon as I merge the changes.
