### ISSUE TITLE
Enable ingress issue

### ISSUE THREAD

**Issue by fzalila** [manusa/actions-setup-minikube#14]
When I try to enable ingress in the minikube cluster, I obtain this error:
```
Run minikube addons enable ingress
  minikube addons enable ingress
  shell: /bin/bash -e {0}
  env:  MINIKUBE_HOME: /home/runner/work/_temp
* Verifying ingress addon...
X enable failed: run callbacks: running callbacks: [create: open /etc/kubernetes/addons/ingress-configmap.yaml: permission denied verifying ingress addon pods : timed out waiting for the condition: timed out waiting for the condition]
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
##[error]Process completed with exit code 70.
```

**Comment by manusa** [comment]
This is working [OK](https://github.com/manusa/actions-setup-minikube/runs/914352373?check_suite_focus=true):
https://github.com/manusa/actions-setup-minikube/blob/3433de7106a2f364e62f7e28a52f04bb220eca06/.github/workflows/runner.yml#L64-L68

I'm not sure what the problem can be when enabling the addon afterwards, but maybe the other approach works for you.

**Comment by fzalila** [comment]
Yes! I tested this (with `start args` and It works). 
Thanks.
