### ISSUE TITLE
Allow users to skip configure environment step

### ISSUE THREAD

**Issue by huang195** [manusa/actions-setup-minikube#16]
In the configure environment step, it deletes /var/lib/docker directory and then installs another version of docker. Since Github Actions build all the needed images before it runs any of the jobs, that means any steps after `manusa/actions-setup-minikube` that make use of a Github Action of Docker kind will fail as it will no longer be able to find that image anymore. It would be better if there's a flag that tells the action to skip re-installing Docker.

**Comment by manusa** [comment]
When I first implemented the action, Minikube was incompatible with the Docker version shipped in GH actions Ubuntu environment.
After a few tests, it seems that this is no longer the case, so I think we can safely remove the Docker daemon replacement step completely.

**Comment by manusa** [comment]
A new [version](https://github.com/manusa/actions-setup-minikube/releases/tag/v2.0.0) was released in the [marketplace](https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster?version=v2.0.0), please check if it works as expected.

**Comment by huang195** [comment]
that's pretty awesome! Thanks, will try it out.
