### ISSUE TITLE
Github has deprecated set-env and add-path

### ISSUE THREAD

**Issue by ghjm** [manusa/actions-setup-minikube#22]
When running this action, the following warnings are produced:
```
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
On October 1st, GitHub posted this:

> Starting today runner version 2.273.5 will begin to warn you if you use the add-path or set-env commands. We are monitoring telemetry for the usage of these commands and plan to fully disable them in the future.

As far as I can see they have not announced a specific date when they will be removing these commands.

**Comment by manusa** [comment]
😨 I use this action in a bunch of projects and didn't notice the warning, thanks for reporting!

I'll provide a fix ASAP.

**Comment by manusa** [comment]
I just released https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster?version=v2.0.1
