### ISSUE TITLE
Support Ubuntu 20.04

### ISSUE THREAD

**Issue by apupier** [manusa/actions-setup-minikube#26]
In readme, it is indicated that only Ubuntu 18.04 is supported.
In job, there is warning mentioning that latest Ubuntu on github action will be 20.04 (can be seen at the bottom here https://github.com/camel-tooling/vscode-camelk/actions/runs/428179049)

https://github.com/actions/virtual-environments/issues/1816

**Comment by manusa** [comment]
Hi @apupier 

Thx for reporting.

Issue has been addressed and a new version has been published to the marketplace:
https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster?version=v2.2.0

**Comment by apupier** [comment]
awesome.
Thanks for the super fast implementation!
