### ISSUE TITLE
Helm available ?

### ISSUE THREAD

**Issue by testillano** [manusa/actions-setup-minikube#38]
I run this workflow and seemed to me that helm was available:

```
Run helm version
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/runner/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/runner/.kube/config
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

Is this provided by github ? (sorry but I'm new with github actions and i didn't see nothing related to helm within your action source code). If not:
Could helm be available for installation here ? It would be a useful setup (docker, kubectl, minikube, helm) for component testing.

BRs

**Comment by manusa** [comment]
Helm is provided by GitHub in its virtual environment (at least for [Ubuntu](https://github.com/actions/virtual-environments/blob/ubuntu20/20210318.0/images/linux/Ubuntu2004-README.md#package-management))

(same as `kubectl` and other [command-line tools](https://github.com/actions/virtual-environments/blob/ubuntu20/20210318.0/images/linux/Ubuntu2004-README.md#tools) cc: @vilajona)

**Comment by testillano** [comment]
thank u
