### ISSUE TITLE
Permissions are too open for `minikube ssh`

### ISSUE THREAD

**Issue by omus** [manusa/actions-setup-minikube#40]
I was attempting to use `minikube ssh --native-ssh=false` and encountered the following error:
```
ssh: Creating ssh client: permissions 0644 for '/home/runner/work/_temp/.minikube/machines/minikube/id_rsa' are too open
```
It appears that the permissions change causing this problem is: https://github.com/manusa/actions-setup-minikube/blob/0461a8b513ae17c37b6749bc0a41f92033191418/src/install.js#L31

**Comment by omus** [comment]
I've worked around this issue by doing:
```
chmod 600 $MINIKUBE_HOME/.minikube/machines/$node/id_rsa
```

**Comment by manusa** [comment]
Thx for reporting, I can try to add a quick fix.

**Comment by manusa** [comment]
Fixed in newest release: https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster?version=v2.4.0
